from enum import Enum
import sys
sys.path.insert(1, './')


class NutrientNameEnum(Enum):
    CALCIUM_CONSTANT = ["CALCIUM", 1087]
    PHOSPHEROUS_CONSTANT = ["PHOSPHEROUS", 1091]
    MAGNESIUM_CONSTANT = ["MAGNESIUM", 1090]
    POTASSIUM_CONSTANT = ["POTASSIUM", 1092]
    SODIUM_CONSTANT = ["SODIUM", 1093]
    IRON_CONSTANT = ["IRON", 1089]
    MANGANESE_CONSTANT = ["MANGANESE", 1101]
    COPPER_CONSTANT = ["COPPER", 1098]
    ZINC_CONSTANT = ["ZINC", 1095]
    PANTOTHONIC_ACID_CONSTANT = ["PANTOTHONIC_ACID", 1170]
    NICACIN_CONSTANT = ["NICACIN", 1167]
    VITAMIN_A_CONSTANT = ["VITAMIN_A", 1104]
    VITAMIN_C_CONSTANT = ["VITAMIN_C", 1162]
    VITAMIN_E_CONSTANT = ["VITAMIN_E", 1109]
    VITAMIN_K_CONSTANT = ["VITAMIN_K", 1185]
    THIAMIN_CONSTANT = ["THIAMIN", 1165]