DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS user_health_info;
DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS meal_contains;
DROP TABLE IF EXISTS meal;
DROP TABLE IF EXISTS plan_contains;
DROP TABLE IF EXISTS plan;
-- DROP TABLE IF EXISTS fdfood;
-- DROP TABLE IF EXISTS foundation_food;
-- DROP TABLE IF EXISTS input_food;
-- DROP TABLE IF EXISTS measure_unit;
-- DROP TABLE IF EXISTS nutrient;
-- DROP TABLE IF EXISTS branded_food;
-- DROP TABLE IF EXISTS fndds_derivation;
-- DROP TABLE IF EXISTS fndds_ingredient_nutrient_value;
-- DROP TABLE IF EXISTS food_calorie_conversion_factor;
-- DROP TABLE IF EXISTS food_category;
-- DROP TABLE IF EXISTS food_component;
-- DROP TABLE IF EXISTS food_nutrient_conversion_factor;
-- DROP TABLE IF EXISTS food_nutrient;
-- DROP TABLE IF EXISTS food_portion;
-- DROP TABLE IF EXISTS food_protein_conversion_factor;
DROP TABLE IF EXISTS nutrient_doses;
DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS user_health_info;
DROP TABLE IF EXISTS user_nutrient_doses;